name: Run Tests
on:
  push:
    branches:
      - main
  release:
    types: [published]
  pull_request:

jobs:
  test:
    name: Test with Python ${{matrix.python}} on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu
        python:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up Python and environment
      uses: lenskit/lkbuild/actions/setup-vanilla-env@main
      with:
        python-version: ${{matrix.python}}

    - name: 🔎 Inspect environment
      run: |
        numba -s

    - name: Run tests
      run: |
        python -m pytest --cov=lenskit_hpf -v

    - name: Aggregate coverage data
      run: coverage xml

    - name: Upload coverage
      uses: codecov/codecov-action@v1

  sdist:
    name: Build Source Packages
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Git tags
      run: git fetch --tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python deps
      run: |
        pip install -U flit
        flit install --deps=production --extras=dev

    - name: Build distribution
      run: flit build

    - name: Save archive
      uses: actions/upload-artifact@v1
      with:
        name: pypi-pkgs
        path: dist

    - name: List dist dir
      run: ls -R dist

    - name: Publish PyPI packages
      if: github.event_name == 'release-disabled'
      run: |
        flit publish
      shell: bash
      env:
        TWINE_NON_INTERACTIVE: y
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}

